name: predictive-maintenance
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.36.0
      - pandas==2.1.4
      - numpy==1.26.4
      - scikit-learn==1.3.2
      - joblib==1.3.2
      - altair==5.2.0
      - protobuf==3.20.3